# 项目相关配置
mkc:
  # 名称
  name: 数据聚合营销云
  # 版本
  version: 4.7.6
  # 版权年份
  copyrightYear: 2023
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/log/uploadPath，Linux配置 /home/ck/uploadPath）
  profile: D:/log/uploadPath
  # 获取ip地址开关
  addressEnabled: true
  workerId: 10001
  datacenterId: 20001


# Shiro
shiro:
  cookie:
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
    # 设置密钥，务必保持唯一性（生成方式，直接拷贝到main运行即可）Base64.encodeToString(CipherUtils.generateNewKey(128, "AES").getEncoded()) （默认启动生成随机秘钥，随机秘钥会导致之前客户端RememberMe Cookie无效，如设置固定秘钥RememberMe Cookie则有效）
    cipherKey: fg0cWVhtLUPBzThGadMs1w==
  rememberMe:
    # 是否开启记住我
    enabled: true


# 数据源配置
# spring配置
spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        # url-pattern: /druid/*
        loginUsername: admin
        loginPassword: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
    dynamic:
      druid:
        initial-size: 5
        min-idle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,slf4j
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        # 后台配置数据源
        master:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://122.228.34.134:5443/test?currentSchema=sysconf&useUnicode=true&characterEncoding=utf-8
          username: test
          password: 123456
        # 业务数据源
        business:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://122.228.34.134:5443/test?currentSchema=business&useUnicode=true&characterEncoding=utf-8
          username: test
          password: 123456
        # 业务数据源
        quartz:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://122.228.34.134:5443/test?currentSchema=quartz&useUnicode=true&characterEncoding=utf-8
          username: test
          password: 123456
          
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: mkc
    password: 123456
    virtualHost: /dev
    listener:
      simple:
        prefetch: 20
  mail:
    host: smtp.feishu.cn
    username: zjbhsk@zjbhsk.com
    password: bbAlTahBsg80ULfh
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true

  # redis配置
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000ms           # 连接超时时长（毫秒）
    lettuce:
      cluster:
        refresh:
          adaptive: true
          period: 20
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
        
# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true

devtools:
    restart:
      # 热部署开关
      enabled: false

monitor:
  mer:
    subject: 【DEV环境】
  notify:
    subject: 【DEV预警】
    email: zhengyuanfang@zjbhsk.com



logging:
  file:
    path: D:/log