
# 数据源配置

# spring配置
spring:
    datasource:
        dynamic:
            druid:
                initial-size: 5
                min-idle: 5
                maxActive: 20
                maxWait: 60000
                timeBetweenEvictionRunsMillis: 60000
                minEvictableIdleTimeMillis: 300000
                validationQuery: SELECT 1
                testWhileIdle: true
                testOnBorrow: false
                testOnReturn: false
                poolPreparedStatements: true
                maxPoolPreparedStatementPerConnectionSize: 20
                filters: stat,slf4j
                connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
            datasource:
                # 后台配置数据源
                master:
                    driver-class-name: org.postgresql.Driver
                    url: jdbc:postgresql://pgm-uf66leh56xvq4a27.pg.rds.aliyuncs.com:5432/baihang?currentSchema=public&useUnicode=true&characterEncoding=utf-8
                    username: test
                    password: 123456
                # 业务数据源
                business:
                    driver-class-name: org.postgresql.Driver
                    url: jdbc:postgresql://pgm-uf66leh56xvq4a27.pg.rds.aliyuncs.com:5432/market?currentSchema=business&useUnicode=true&characterEncoding=utf-8
                    username: test
                    password: 123456
                # 业务数据源
                quartz:
                    driver-class-name: org.postgresql.Driver
                    url: jdbc:postgresql://pgm-uf66leh56xvq4a27.pg.rds.aliyuncs.com:5432/baihang?currentSchema=quartz&useUnicode=true&characterEncoding=utf-8
                    username: test
                    password: 123456

    # redis配置
    redis:
        database: 0
        host: redis-server
        port: 6379
        password:
        timeout: 2000ms           # 连接超时时长（毫秒）
        lettuce:
            pool:
                max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
                max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-idle: 10      # 连接池中的最大空闲连接
                min-idle: 5       # 连接池中的最小空闲连接

    rabbitmq:
        host: 192.168.252.10
        port: 5672
        username: mkc
        password: 123456
        virtualHost: /test
        listener:
            simple:
                prefetch: 20
    mail:
        host: smtp.qt300061.com
        username: market_sys@qt300061.com
        password: Q^3H2!46dJ8
        port: 465
        properties:
            mail:
                smtp:
                    ssl:
                        enable: true
                    auth: true
                    starttls:
                        enable: true
                        required: true
#    ding:
#        syserr:
#            token:
#            secret:
#        business:
#            token:
#            secret:
# 日志配置
logging:
    file:
        path: /opt/app/log


monitor:
    mer:
        subject: 【测试环境】
    notify:
        subject: 【测试预警】
        email: test@test.com