
# 数据源配置
# spring配置
spring:
    datasource:
        dynamic:
            druid:
                initial-size: 5
                min-idle: 5
                maxActive: 20
                maxWait: 60000
                timeBetweenEvictionRunsMillis: 60000
                minEvictableIdleTimeMillis: 300000
                validationQuery: SELECT 1
                testWhileIdle: true
                testOnBorrow: false
                testOnReturn: false
                poolPreparedStatements: true
                maxPoolPreparedStatementPerConnectionSize: 20
                filters: stat,slf4j
                connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
            datasource:
                # 后台配置数据源
                master:
                    driver-class-name: org.postgresql.Driver
                    url: jdbc:postgresql://127.0.0.1:5432/dev?currentSchema=sysconf&useUnicode=true&characterEncoding=utf-8
                    username: test
                    password: 123456
                # 业务数据源
                business:
                    driver-class-name: org.postgresql.Driver
                    url: jdbc:postgresql://127.0.0.1:5432/dev?currentSchema=business&useUnicode=true&characterEncoding=utf-8
                    username: test
                    password: 123456
                # 业务数据源
                quartz:
                    driver-class-name: org.postgresql.Driver
                    url: jdbc:postgresql://127.0.0.1:5432/dev?currentSchema=quartz&useUnicode=true&characterEncoding=utf-8
                    username: test
                    password: 123456
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: mkc
        password: 123456
        virtualHost: /dev
        listener:
            simple:
                prefetch: 20
    mail:
        host: smtp.feishu.cn
        username: zjbhsk@zjbhsk.com
        password: bbAlTahBsg80ULfh
        port: 465
        properties:
            mail:
                smtp:
                    ssl:
                        enable: true
                    auth: true
                    starttls:
                        enable: true
                        required: true
#    ding:
#        syserr:
#            token: 6a93cb682ac609b78c504938f87e39dee3fff0a0e448d9b82972c4e4f6fbb0ef
#            secret: SEC39cf5cfe0d5d43b8dd75293e42f579070cf4164f8b75e0383f59aee6b340b2aa
#        business:
#            token: 6a93cb682ac609b78c504938f87e39dee3fff0a0e448d9b82972c4e4f6fbb0ef
#            secret: SEC39cf5cfe0d5d43b8dd75293e42f579070cf4164f8b75e0383f59aee6b340b2aa



    # redis配置
    redis:
        database: 1
        host: 127.0.0.1
        port: 6379
        password:
        timeout: 1000ms           # 连接超时时长（毫秒）
        lettuce:
            pool:
                max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
                max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-idle: 10      # 连接池中的最大空闲连接
                min-idle: 5       # 连接池中的最小空闲连接

logging:
    file:
        path: D:/log

monitor:
    mer:
        subject: 【DEV环境】
    notify:
        subject: 【DEV预警】
        email: zhengyuanfang@zjbhsk.com